GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/38726569-acd0-4f04-839d-485d7e417348


###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Movie"
}

###

PUT http://localhost:3000/categories/38726569-acd0-4f04-839d-485d7e417348
Content-Type: application/json

{
    "name": "Movie1111"
}

###

DELETE http://localhost:3000/categories/38726569-acd0-4f04-839d-485d7e417348
Content-Type: application/json