GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/9b46d94a-895a-48aa-ba61-16e3005bb41c


###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "id": null,
    "name": "Fiction 3",
    "description": "Fiction books"

}

###

PUT http://localhost:3000/categories/dc803284-f8c8-40fb-89d1-971fe36c0e28
Content-Type: application/json

{
    "name": "Movie1111"
}

###

DELETE http://localhost:3000/categories/38726569-acd0-4f04-839d-485d7e417348
Content-Type: application/json